### PR TITLE
use new k8s registry

### LINKED ISSUE #43: Migrate from k8s.gcr.io to registry.k8s.io
Fixes https://github.com/kubernetes/k8s.io/issues/4780

### PR DESCRIPTION
**Pull request by yuvraj9**
This PR migrate from k8s.gcr.io to registry.k8s.io

Fixes #43 
Fixes https://github.com/kubernetes/k8s.io/issues/4780

### CODE REVIEW

**Comment by kakaZhou719** [comment]
@Stevent-fei ,could you help to confirm whether this modification is compatible?

**Comment by yuvraj9** [comment]
@Stevent-fei @kakaZhou719 can you merge this?

**Comment by Stevent-fei** [comment]
ok

**Comment by Stevent-fei** [comment]
@yuvraj9 This modification will lead to incompatibility. After the modification, there will be some problems. It will not be merged into the main branch first.

let me check the cause of the problem first

**Comment by yuvraj9** [comment]
@Stevent-fei just a reminder for this. Also let me know if i can help in someway.

**Comment by ahmedwaleedmalik** [comment]
@Stevent-fei any update on this?

**Comment by Stevent-fei** [comment]
> @Stevent-fei any update on this?

@ahmedwaleedmalik @yuvraj9 I am ready to merge this code into the main branch, and the issue has been resolved.

**Pull request merged**
